### ISSUE TITLE
Not compatible with BubbleBuffs

### ISSUE THREAD

**Issue by nexusno2000** [xADDBx/MorePartySlots#1]
It's a great mod, but since it's not compatible with BubbleBuffs (can't bring up the buff config screen), I can't use it. Sad.

**Comment by xADDBx** [comment]
Surprisingly it really is incompatible.

I might need to look into it then...

**Comment by xADDBx** [comment]
This might be an issue in where if you change the party size after BubbleBuffs was initialized, it'll behave incorrectly until you restart?

Honestly I can't reproduce the issue. The other person who did manage to reproduce it yesterday couldn't do it anymore today.

**Comment by nexusno2000** [comment]
I did some further testing and got BBuffs + 8 slots to work just fine. I'm not really 100% sure what the issue was last time, but it's probably something to do with changing parameters before BB was initiated.

Anyway. Great mod!
